--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.505.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2022.04.24. 17:33:32
-- Server version: 10.4.22
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS educrypto;

CREATE DATABASE IF NOT EXISTS educrypto
	CHARACTER SET utf8mb4
	COLLATE utf8mb4_general_ci;

--
-- Set default database
--
USE educrypto;

--
-- Create table `groups`
--
CREATE TABLE IF NOT EXISTS groups (
  Id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  startBudget DECIMAL(65, 30) NOT NULL,
  startDate DATETIME NOT NULL,
  finishDate DATETIME NOT NULL,
  isFinished TINYINT(1) NOT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create index `IX_Groups_name` on table `groups`
--
ALTER TABLE groups 
  ADD UNIQUE INDEX IX_Groups_name(name);

--
-- Create table `userhandlings`
--
CREATE TABLE IF NOT EXISTS userhandlings (
  Id INT(11) NOT NULL AUTO_INCREMENT,
  userName VARCHAR(100) NOT NULL,
  PasswordHash VARCHAR(100) NOT NULL DEFAULT '',
  email VARCHAR(100) NOT NULL,
  fullName VARCHAR(100) NOT NULL DEFAULT '',
  birthDate DATETIME NOT NULL,
  xpLevel INT(11) NOT NULL,
  moneyDollar DECIMAL(65, 30) NOT NULL DEFAULT 0.000000000000000000000000000000,
  walletNumber VARCHAR(34) DEFAULT NULL,
  profilePictureUrl LONGTEXT DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create index `IX_UserHandlings_email` on table `userhandlings`
--
ALTER TABLE userhandlings 
  ADD UNIQUE INDEX IX_UserHandlings_email(email);

--
-- Create index `IX_UserHandlings_userName` on table `userhandlings`
--
ALTER TABLE userhandlings 
  ADD UNIQUE INDEX IX_UserHandlings_userName(userName);

--
-- Create index `IX_UserHandlings_walletNumber` on table `userhandlings`
--
ALTER TABLE userhandlings 
  ADD UNIQUE INDEX IX_UserHandlings_walletNumber(walletNumber);

--
-- Create table `userforgroups`
--
CREATE TABLE IF NOT EXISTS userforgroups (
  Id INT(11) NOT NULL AUTO_INCREMENT,
  userHandlingModelId INT(11) NOT NULL DEFAULT 0,
  accesLevel VARCHAR(50) NOT NULL,
  groupWalletNumber VARCHAR(34) DEFAULT NULL,
  money DECIMAL(65, 30) NOT NULL,
  groupModelId INT(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create index `IX_UserForGroups_groupModelId` on table `userforgroups`
--
ALTER TABLE userforgroups 
  ADD INDEX IX_UserForGroups_groupModelId(groupModelId);

--
-- Create index `IX_UserForGroups_groupWalletNumber` on table `userforgroups`
--
ALTER TABLE userforgroups 
  ADD UNIQUE INDEX IX_UserForGroups_groupWalletNumber(groupWalletNumber);

--
-- Create index `IX_UserForGroups_userHandlingModelId` on table `userforgroups`
--
ALTER TABLE userforgroups 
  ADD INDEX IX_UserForGroups_userHandlingModelId(userHandlingModelId);

--
-- Create foreign key
--
ALTER TABLE userforgroups 
  ADD CONSTRAINT FK_UserForGroups_Groups_groupModelId FOREIGN KEY (groupModelId)
    REFERENCES groups(Id) ON DELETE CASCADE;

--
-- Create foreign key
--
ALTER TABLE userforgroups 
  ADD CONSTRAINT FK_UserForGroups_UserHandlings_userHandlingModelId FOREIGN KEY (userHandlingModelId)
    REFERENCES userhandlings(Id) ON DELETE CASCADE;

--
-- Create table `usertradehistories`
--
CREATE TABLE IF NOT EXISTS usertradehistories (
  Id INT(11) NOT NULL AUTO_INCREMENT,
  userHandlingModelId INT(11) NOT NULL DEFAULT 0,
  userForGroupsModelId INT(11) DEFAULT NULL,
  tradeDate DATETIME DEFAULT NULL,
  spentValue DECIMAL(65, 30) NOT NULL,
  boughtValue DECIMAL(65, 30) NOT NULL,
  boughtCryptoSymbol LONGTEXT DEFAULT NULL,
  spentCryptoSymbol LONGTEXT DEFAULT NULL,
  actualPrice DECIMAL(65, 30) NOT NULL DEFAULT 0.000000000000000000000000000000,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create index `IX_UserTradeHistories_userForGroupsModelId` on table `usertradehistories`
--
ALTER TABLE usertradehistories 
  ADD INDEX IX_UserTradeHistories_userForGroupsModelId(userForGroupsModelId);

--
-- Create index `IX_UserTradeHistories_userHandlingModelId` on table `usertradehistories`
--
ALTER TABLE usertradehistories 
  ADD INDEX IX_UserTradeHistories_userHandlingModelId(userHandlingModelId);

--
-- Create foreign key
--
ALTER TABLE usertradehistories 
  ADD CONSTRAINT FK_UserTradeHistories_UserForGroups_userForGroupsModelId FOREIGN KEY (userForGroupsModelId)
    REFERENCES userforgroups(Id);

--
-- Create foreign key
--
ALTER TABLE usertradehistories 
  ADD CONSTRAINT FK_UserTradeHistories_UserHandlings_userHandlingModelId FOREIGN KEY (userHandlingModelId)
    REFERENCES userhandlings(Id) ON DELETE CASCADE;

--
-- Create table `usercryptos`
--
CREATE TABLE IF NOT EXISTS usercryptos (
  Id INT(11) NOT NULL AUTO_INCREMENT,
  userHandlingModelId INT(11) NOT NULL DEFAULT 0,
  cryptoValue DECIMAL(65, 30) NOT NULL,
  isFavourite TINYINT(1) NOT NULL,
  userForGroupsModelId INT(11) DEFAULT NULL,
  cryptoSymbol LONGTEXT NOT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create index `IX_UserCryptos_userForGroupsModelId` on table `usercryptos`
--
ALTER TABLE usercryptos 
  ADD INDEX IX_UserCryptos_userForGroupsModelId(userForGroupsModelId);

--
-- Create index `IX_UserCryptos_userHandlingModelId` on table `usercryptos`
--
ALTER TABLE usercryptos 
  ADD INDEX IX_UserCryptos_userHandlingModelId(userHandlingModelId);

--
-- Create foreign key
--
ALTER TABLE usercryptos 
  ADD CONSTRAINT FK_UserCryptos_UserForGroups_userForGroupsModelId FOREIGN KEY (userForGroupsModelId)
    REFERENCES userforgroups(Id);

--
-- Create foreign key
--
ALTER TABLE usercryptos 
  ADD CONSTRAINT FK_UserCryptos_UserHandlings_userHandlingModelId FOREIGN KEY (userHandlingModelId)
    REFERENCES userhandlings(Id) ON DELETE CASCADE;

--
-- Create table `__efmigrationshistory`
--
CREATE TABLE IF NOT EXISTS __efmigrationshistory (
  MigrationId VARCHAR(150) NOT NULL,
  ProductVersion VARCHAR(32) NOT NULL,
  PRIMARY KEY (MigrationId)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 1820,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

-- 
-- Dumping data for table groups
--
INSERT INTO groups VALUES
(1, 'test', 100.000000000000000000000000000000, '0001-01-01 00:00:00', '2022-05-01 00:00:00', 0);

-- 
-- Dumping data for table userhandlings
--
INSERT INTO userhandlings VALUES
(1, 'test', 'wSg08QMfZJchTyfUQy8mUXrUlBVsuI1RK9sdxLV9staSo9+iaaGbCgoqD9fWoqiF4zyDnJPCBtowoYc5KEftJw==', 'test@test.com', 'Test Elek', '2000-01-01 00:00:00', 0, 1000.000000000000000000000000000000, NULL, NULL),
(2, 'replica', 'eCf8a+CB6qaYDSy/BEj0sRgzVo4OWseUL/qLhw1a9hWeVX3qNK4DUis3RJif6pFYuur1t0ttU95UsJMe0eBJSg==', 'replica@wallas.com', 'Officer K', '2049-01-01 00:00:00', 0, 1000.000000000000000000000000000000, NULL, NULL);

-- 
-- Dumping data for table userforgroups
--
INSERT INTO userforgroups VALUES
(1, 1, 'creator', NULL, 100.000000000000000000000000000000, 1),
(2, 2, 'member', NULL, 100.000000000000000000000000000000, 1);

-- 
-- Dumping data for table __efmigrationshistory
--
INSERT INTO __efmigrationshistory VALUES
('20220113160850_Initial', '5.0.13'),
('20220117090535_EduCrypto_v2', '5.0.13'),
('20220127083328_EduCrypto_v2.1', '5.0.13'),
('20220206164755_EduCrypto_v2.2', '5.0.13'),
('20220211102923_EduCrypto_v3.0', '5.0.13'),
('20220211103329_EduCrypto_v3.1', '5.0.13'),
('20220306125000_EduCrypto_v3.2', '5.0.13'),
('20220330092058_EduCrypto_v4.0', '5.0.13'),
('20220405102850_EduCrypto_v4.1', '5.0.13');

-- 
-- Dumping data for table usertradehistories
--
-- Table educrypto.usertradehistories does not contain any data (it is empty)

-- 
-- Dumping data for table usercryptos
--
-- Table educrypto.usercryptos does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;